name: test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
concurrency:
  group: test-commit-windows-${{ github.ref_name =='main' && github.run_id || github.ref }}${{github.run_attempt != 1 && github.run_id  || ''}}
  cancel-in-progress: ${{ github.ref_name =='main' }}
jobs:
  test:
    name: ${{ matrix.platform }} / ${{ matrix.node-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
        fail-fast: false
        matrix:
            platform: [ubuntu-latest, windows-latest, macos-latest]
            node-version: [18,20] 
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i

      - run: npm run build

      - run: yarn run test